<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6650" started-at="2019-12-20T07:02:38Z" finished-at="2019-12-20T07:02:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6650" started-at="2019-12-20T07:02:38Z" finished-at="2019-12-20T07:02:45Z">
      <class name="Jenkins_new_Java.testing">
        <test-method status="FAIL" signature="getData()[pri:0, instance:Jenkins_new_Java.testing@3a82f6ef]" name="getData" duration-ms="16" started-at="2019-12-20T01:02:38Z" finished-at="2019-12-20T01:02:38Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)
	at junit.framework.Assert.fail(Assert.java:56)
	at Jenkins_new_Java.testing.getData(testing.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getData -->
        <test-method status="PASS" signature="login1()[pri:0, instance:Jenkins_new_Java.testing@3a82f6ef]" name="login1" duration-ms="5388" started-at="2019-12-20T01:02:38Z" finished-at="2019-12-20T01:02:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login1 -->
        <test-method status="PASS" signature="tear()[pri:0, instance:Jenkins_new_Java.testing@3a82f6ef]" name="tear" is-config="true" duration-ms="1226" started-at="2019-12-20T01:02:44Z" finished-at="2019-12-20T01:02:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- Jenkins_new_Java.testing -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
